# Generated by Django 4.2.3 on 2023-10-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_alter_task_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='DueDate',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Title',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Priority',
        ),
    ]
